Repository ZynerOrg/xyter, pull requests merged in 2022-04, with the labels that each got.

#189 Remove trailing comma resulting in error
  config.json.example
Labels: size/XS

#195 Typescript error and package error
  package.json
Labels: size/XS

#196 📝 Docs regarding pterodactyl
  README.md
Labels: size/XS

#199 GDPR fix when saving data
  src/commands/admin/credits/modules/give.ts
  src/commands/admin/credits/modules/set.ts
  src/commands/admin/credits/modules/take.ts
  src/commands/admin/credits/modules/transfer.ts
  src/commands/credits/modules/balance.ts
  src/commands/credits/modules/gift.ts
  src/commands/credits/modules/work.ts
  src/commands/profile/modules/view.ts
  src/commands/reputation/modules/give.ts
  src/commands/settings/user/modules/appearance.ts
  src/commands/shop/modules/pterodactyl.ts
  src/commands/shop/roles/modules/buy.ts
  src/commands/shop/roles/modules/cancel.ts
  src/events/guildCreate/index.ts
  src/events/guildDelete/index.ts
  src/events/guildMemberAdd/index.ts
  src/events/guildMemberRemove/index.ts
  src/events/interactionCreate/index.ts
  src/events/messageCreate/index.ts
  src/events/messageCreate/modules/counters.ts
  src/events/messageUpdate/index.ts
  src/events/ready/index.ts
  src/handlers/schedules.ts
  src/helpers/database/models/userSchema.ts
  src/helpers/dropGuild.ts
  src/helpers/dropUser.ts
  src/helpers/fetchGuild.ts
  src/helpers/fetchUser.ts
  src/helpers/updatePresence.ts
  src/index.ts
Labels: size/XL

#202 Fixed code smells
  src/commands/admin/counters/index.ts
  src/commands/admin/counters/modules/add.ts
  src/commands/admin/counters/modules/remove.ts
  src/commands/admin/credits/index.ts
  src/commands/admin/credits/modules/give.ts
  src/commands/admin/credits/modules/set.ts
  src/commands/admin/credits/modules/take.ts
  src/commands/admin/credits/modules/transfer.ts
  src/commands/admin/index.ts
  src/commands/counters/index.ts
  src/commands/counters/modules/view.ts
  src/commands/credits/index.ts
  src/commands/credits/modules/balance.ts
  src/commands/credits/modules/gift.ts
  src/commands/credits/modules/top.ts
  src/commands/credits/modules/work.ts
  src/commands/profile/index.ts
  src/commands/profile/modules/view.ts
  src/commands/reputation/modules/give.ts
  src/commands/settings/guild/addons/credits.ts
  src/commands/settings/guild/addons/points.ts
  src/commands/settings/guild/addons/pterodactyl.ts
  src/commands/settings/guild/index.ts
  src/commands/settings/user/modules/appearance.ts
  src/commands/shop/index.ts
  src/commands/shop/modules/pterodactyl.ts
  src/commands/shop/roles/modules/buy.ts
  src/commands/shop/roles/modules/cancel.ts
  src/commands/utilities/index.ts
  src/commands/utilities/modules/about.ts
  src/commands/utilities/modules/lookup.ts
  src/commands/utilities/modules/stats.ts
Labels: size/L

#203 201 fix code smells
  src/commands/admin/counters/modules/add.ts
Labels: size/M

#204 Encryption
  config.json.example
  src/commands/settings/guild/addons/pterodactyl.ts
  src/commands/shop/modules/pterodactyl.ts
  src/handlers/encryption.ts
  src/helpers/database/models/apiSchema.ts
Labels: size/L

#205 Fix admin commands
  src/commands/admin/credits/modules/give.ts
  src/commands/admin/credits/modules/set.ts
  src/commands/admin/credits/modules/take.ts
  src/commands/admin/credits/modules/transfer.ts
Labels: size/L

#207 📦 add pino-pretty
  package.json
Labels: size/XS

#208 ✨ shop role colors and devMode and fix delete role
  config.json.example
  src/commands/shop/index.ts
  src/commands/shop/roles/modules/buy.ts
  src/events/ready/index.ts
  src/handlers/schedules.ts
  src/helpers/deployCommands.ts
Labels: size/M

#209 Refactoring code and updated vscode configurations
  .cspell/custom-dictionary-workspace.txt
  .vscode/extensions.json
  .vscode/settings.json
  docs/_config.yml
  docs/index.md
  src/commands/shop/roles/modules/buy.ts
  src/events/guildMemberAdd/index.ts
  src/events/guildMemberRemove/index.ts
  src/events/messageCreate/index.ts
  src/events/messageCreate/modules/counters.ts
  src/events/messageCreate/modules/credits.ts
  src/events/messageCreate/modules/points.ts
  src/handlers/commands.ts
  src/handlers/events.ts
  src/handlers/index.ts
  src/handlers/locale.ts
  src/handlers/logger.ts
  src/helpers/database/index.ts
  src/helpers/database/models/counterSchema.ts
  src/helpers/database/models/guildSchema.ts
  src/helpers/database/models/index.ts
  src/helpers/database/models/shopRolesSchema.ts
  src/helpers/database/models/timeoutSchema.ts
  src/helpers/dbGuildFix.ts
  src/helpers/dbMemberFix.ts
  src/helpers/deployCommands.ts
  src/helpers/dropGuild.ts
  src/helpers/index.ts
  src/helpers/saveUser.ts
Labels: size/XXL

#211 🐛 not removing role and taking negative payed
  src/handlers/schedules.ts
Labels: size/S

#212 ✏️ shop cancel is now shop roles cancel
  src/commands/shop/index.ts
Labels: size/S

#213 🐛 shop roles cancel instead of shop cancel
  src/commands/shop/index.ts
Labels: size/S

#214 🐛 cancel should now work
  src/commands/shop/index.ts
Labels: size/S

#216 🚑 fix user deleting non shopRoles
  src/commands/shop/roles/modules/cancel.ts
Labels: size/XS

#219 Organize and structure plugins
  src/config/example.encryption.ts
  src/database/index.ts
  src/database/schemas/api.ts
  src/database/schemas/counter.ts
  src/database/schemas/index.ts
  src/database/schemas/shopRole.ts
  src/database/schemas/timeout.ts
  src/events/guildCreate/index.ts
  src/events/guildDelete/index.ts
  src/events/guildMemberAdd/index.ts
  src/events/guildMemberRemove/index.ts
  src/events/interactionCreate/components/isCommand.ts
  src/events/interactionCreate/index.ts
  src/handlers/encryption.ts
  src/helpers/devMode.ts
Labels: size/L

#220 🚑 deployCommands should work
  src/handlers/commands.ts
  src/handlers/deployCommands.ts
  src/helpers/devMode.ts
Labels: size/M

#222 🚑 credits balance
  src/plugins/credits/modules/balance/index.ts
Labels: size/XS

#223 Refactorize code
  src/events/messageCreate/index.ts
  src/events/messageCreate/modules/counters.ts
  src/events/messageCreate/modules/counters/index.ts
  src/events/messageCreate/modules/credits.ts
  src/events/messageCreate/modules/credits/index.ts
  src/events/messageCreate/modules/index.ts
  src/events/messageCreate/modules/points.ts
  src/events/messageCreate/modules/points/index.ts
  src/schedules/jobs/shopRoles.ts
  tsconfig.json
Labels: size/L

#235 2022.4.1
  src/database/schemas/guild.ts
  src/events/messageCreate/index.ts
  src/plugins/settings/guild/index.ts
  src/plugins/settings/guild/modules/shop.ts
  src/plugins/shop/roles/index.ts
Labels: size/L

#236 2022.4.2
  src/events/messageCreate/modules/counters/index.ts
Labels: size/S

#237 2022.4.3
  src/events/messageCreate/modules/counters/index.ts
  src/events/messageDelete/index.ts
  src/events/messageDelete/modules/counter.ts
Labels: size/M

#238 2022.4.4
  src/events/messageDelete/modules/counter.ts
Labels: size/XS

#239 2022.4.5
  src/events/messageDelete/modules/counter.ts
Labels: size/S

#247 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/L

#251 Added german
  src/locale/index.ts
Labels: size/M

#253 L10n main
  lang/en/plugins.json
Labels: size/XS
