Repository ZynerOrg/xyter, pull requests merged in 2022-10, with the labels that each got.

#421 🧑‍💻 Fixed some code smells
  src/managers/command/index.ts
  src/managers/event/index.ts
  src/plugins/commands/counters/modules/view/index.ts
  src/plugins/commands/manage/modules/credits/modules/transfer/index.ts
  src/plugins/commands/shop/modules/roles/modules/cancel/index.ts
Labels: size/M

#422 🚑 Fixed some syntax error
  src/plugins/commands/credits/modules/gift/index.ts
  src/plugins/commands/credits/modules/work/index.ts
Labels: size/M

#423 Fix some code smells
  src/plugins/commands/config/index.ts
  src/plugins/commands/credits/modules/gift/index.ts
  src/plugins/commands/manage/modules/credits/index.ts
Labels: size/M

#424 🧑‍💻 Fixed some more code smells again
  src/plugins/events/messageUpdate/audits.ts
  src/plugins/events/messageUpdate/modules/counter.ts
  src/plugins/events/rateLimit/index.ts
Labels: size/S

#425 🧑‍💻 Fixed more code smells
  src/plugins/events/messageCreate/modules/credits/index.ts
  src/plugins/events/messageCreate/modules/points/index.ts
  src/plugins/events/messageDelete/audits.ts
Labels: size/M

#426 🧑‍💻 Fixed some more code smells
  src/plugins/events/interactionCreate/handlers/button/index.ts
  src/plugins/events/interactionCreate/handlers/command/index.ts
  src/plugins/events/interactionCreate/index.ts
Labels: size/S

#427 Fixed some more code smells
  src/plugins/commands/manage/index.ts
  src/plugins/commands/shop/modules/cpgg/index.ts
  src/plugins/commands/shop/modules/roles/modules/buy/index.ts
  src/plugins/events/interactionCreate/handlers/index.ts
  src/plugins/events/messageCreate/modules/counters/index.ts
Labels: size/M

#428 More code smells fixed
  src/managers/database/index.ts
  src/plugins/events/interactionCreate/audits.ts
Labels: size/S

#429 🧑‍💻 Fixed some more code smells
  src/plugins/commands/manage/modules/credits/modules/take/index.ts
  src/plugins/commands/moderation/index.ts
  src/plugins/commands/profile/index.ts
  src/plugins/commands/reputation/modules/give/components/noSelfReputation.ts
  src/plugins/commands/shop/index.ts
  src/plugins/commands/utility/index.ts
  src/plugins/events/guildMemberAdd/audits.ts
  src/plugins/events/guildMemberRemove/audits.ts
Labels: size/M

#430 🧑‍💻 Fixed some more code smells
  src/plugins/commands/dns/index.ts
  src/plugins/commands/fun/modules/meme/index.ts
  src/plugins/commands/manage/modules/counters/index.ts
  src/plugins/commands/manage/modules/counters/modules/add/index.ts
  src/plugins/commands/manage/modules/counters/modules/remove/index.ts
  src/plugins/commands/manage/modules/credits/modules/give/index.ts
Labels: size/L

#431 🧑‍💻 Fixed some more code smells
  src/jobs/shop/modules/roles/components/overDueForPayment.ts
  src/jobs/timeouts/index.ts
  src/plugins/commands/config/modules/audits/index.ts
  src/plugins/commands/config/modules/cpgg/index.ts
  src/plugins/commands/config/modules/credits/index.ts
  src/plugins/commands/config/modules/embeds/index.ts
  src/plugins/commands/config/modules/points/index.ts
  src/plugins/commands/config/modules/shop/index.ts
  src/plugins/commands/config/modules/welcome/index.ts
  src/plugins/commands/reputation/modules/give/index.ts
Labels: size/M

#432 Dev
  PRIVACY.md
  docker-compose.dev.yml
  docker-compose.yml
Labels: size/L

#442 Update command_request.yaml
  .github/ISSUE_TEMPLATE/command_request.yaml
Labels: size/XS

#446 More code smell fixes
  examples/addGuildAndGuildOwner.ts
  examples/createGuildCounter.ts
  examples/createGuildMember.ts
  examples/deleteGuildCounter.ts
  examples/deleteGuildMember.ts
  examples/dropGuild.ts
  examples/findUniqueChannelCounter.ts
  examples/getGuildMember.ts
  examples/updateGuildCounter.ts
  src/helpers/transferCredits/index.ts
Labels: size/L

#447 More code smell fixing
  src/events/guildCreate/index.ts
  src/events/guildDelete/index.ts
  src/events/guildMemberAdd/index.ts
  src/events/guildMemberRemove/index.ts
  src/events/ready/index.ts
  src/handlers/cooldown/index.ts
  src/handlers/deployCommands/index.ts
  src/handlers/devMode/index.ts
  src/handlers/updatePresence/index.ts
  src/helpers/addSeconds/index.ts
  src/helpers/checkDirectory/index.ts
  src/index.ts
  src/schedules/shop/index.ts
  src/schedules/timeouts/index.ts
Labels: size/M

#449 💡 Start critical handlers
  src/index.ts
Labels: size/XS

#450 💡 Start main process
  src/index.ts
Labels: size/XS

#454 Fix a bug around dev guild commands and added an helper to reduce duplicated code for embed builders
  src/handlers/deployCommands/index.ts
  src/helpers/baseEmbeds/index.ts
Labels: size/M

#456 ♻️ Credits module
  src/commands/credits/index.ts
  src/commands/credits/modules/balance/index.ts
  src/commands/credits/modules/gift/index.ts
  src/commands/credits/modules/top/index.ts
  src/commands/credits/modules/work/index.ts
Labels: size/XL

#457 438 bug credits gift value overflow when gifting more than 2147483662
  src/commands/credits/modules/gift/index.ts
  src/helpers/transferCredits/index.ts
Labels: size/S

#459 Dev 2022.11.01
  .env.example
  .eslintrc.json
  .github/workflows/docker-image.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  prisma/migrations/20221019063840_init/migration.sql
  prisma/migrations/20221019064232_init/migration.sql
  prisma/migrations/20221019081114_modules/migration.sql
  prisma/migrations/20221019081816_modules/migration.sql
  prisma/migrations/20221019113258_modules/migration.sql
  prisma/migrations/20221019114543_modules/migration.sql
  prisma/migrations/20221019142757_modules/migration.sql
  prisma/migrations/20221019153247_cooldowns/migration.sql
  prisma/migrations/20221019153652_audit_dates/migration.sql
  prisma/migrations/20221019172846_embedconfig/migration.sql
  prisma/migrations/20221020081238_cpgg_api/migration.sql
  prisma/migrations/20221020084750_cooldown_string/migration.sql
  prisma/migrations/20221020084922_cooldown_int/migration.sql
  prisma/migrations/20221020111948_audits_module/migration.sql
  prisma/migrations/20221020113312_shop_module/migration.sql
  prisma/migrations/20221020113704_welcome_module/migration.sql
  prisma/migrations/20221020113756_welcome_module_correction/migration.sql
  prisma/migrations/20221020113831_welcome_module_correction/migration.sql
  prisma/migrations/20221021150615_shoproles_model/migration.sql
  prisma/migrations/20221021151136_shoproles_model_correction/migration.sql
  prisma/migrations/20221021151337_shoproles_model_correction/migration.sql
  prisma/migrations/20221021153546_shoproles_model_correction/migration.sql
  prisma/migrations/20221021172156_int_to_bigint/migration.sql
  prisma/migrations/20221021172345_bigint_to_int/migration.sql
  prisma/migrations/20221023164351_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/commands/counters/index.ts
  src/commands/counters/modules/view/index.ts
  src/commands/credits/modules/gift/index.ts
  src/commands/manage/modules/credits/modules/transfer/index.ts
  src/events/messageCreate/modules/counters/index.ts
  src/events/messageUpdate/modules/counter.ts
  src/helpers/checkDirectory/index.ts
  src/helpers/credits/index.ts
  tsconfig.json
Labels: size/XXL

#461 2022.11.02
  src/events/interactionCreate/index.ts
Labels: size/XS

#464 Use Alpine as base image in docker
  Dockerfile
Labels: size/XS

#462 Refactoring some handlers and middlewares
  package-lock.json
  package.json
  src/commands/credits/modules/gift/index.ts
  src/commands/credits/modules/work/index.ts
  src/commands/fun/modules/meme/index.ts
  src/commands/manage/modules/credits/modules/give/index.ts
  src/commands/manage/modules/credits/modules/set/index.ts
  src/commands/manage/modules/credits/modules/take/index.ts
  src/commands/manage/modules/credits/modules/transfer/index.ts
  src/commands/reputation/modules/give/index.ts
  src/events/interactionCreate/handlers/button/index.ts
  src/events/interactionCreate/handlers/command/index.ts
  src/events/messageCreate/modules/credits/index.ts
  src/events/messageCreate/modules/points/index.ts
  src/events/ready/index.ts
  src/handlers/command/index.ts
  src/handlers/cooldown/index.ts
  src/handlers/database/index.ts
  src/handlers/deployCommands/index.ts
  src/handlers/devMode/index.ts
  src/handlers/event/index.ts
  src/handlers/schedule/index.ts
  src/handlers/updatePresence/index.ts
  src/helpers/addSeconds/index.ts
  src/helpers/credits/give.ts
  src/helpers/credits/set.ts
  src/helpers/credits/take.ts
  src/helpers/credits/transactionRules.ts
  src/helpers/credits/transfer.ts
  src/index.ts
  src/middlewares/cooldown/index.ts
  src/schedules/cooldowns/index.ts
  src/schedules/timeouts/index.ts
Labels: size/XXL

#465 2022.11.03
  Dockerfile
  package-lock.json
  package.json
  src/commands/credits/modules/gift/index.ts
  src/commands/credits/modules/work/index.ts
  src/commands/fun/modules/meme/index.ts
  src/commands/manage/modules/credits/modules/give/index.ts
  src/commands/manage/modules/credits/modules/set/index.ts
  src/commands/manage/modules/credits/modules/take/index.ts
  src/commands/manage/modules/credits/modules/transfer/index.ts
  src/commands/reputation/modules/give/index.ts
  src/events/interactionCreate/handlers/button/index.ts
  src/events/interactionCreate/handlers/command/index.ts
  src/events/messageCreate/modules/credits/index.ts
  src/events/messageCreate/modules/points/index.ts
  src/events/ready/index.ts
  src/handlers/command/index.ts
  src/handlers/cooldown/index.ts
  src/handlers/database/index.ts
  src/handlers/deployCommands/index.ts
  src/handlers/devMode/index.ts
  src/handlers/event/index.ts
  src/handlers/schedule/index.ts
  src/handlers/updatePresence/index.ts
  src/helpers/addSeconds/index.ts
  src/helpers/credits/give.ts
  src/helpers/credits/set.ts
  src/helpers/credits/take.ts
  src/helpers/credits/transactionRules.ts
  src/helpers/credits/transfer.ts
  src/index.ts
  src/middlewares/cooldown/index.ts
  src/schedules/cooldowns/index.ts
  src/schedules/timeouts/index.ts
Labels: size/XXL
